version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: evil_mescours_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: evil_user
      POSTGRES_PASSWORD: evil_password
      POSTGRES_DB: evil_mescours_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
