name: CI SAE-BUT3

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  verification-qualite:
    name: Vérification du code
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      # --- TESTS FRONT-END ---
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Installation et Linting Front-end (React/ESLint)
        run: |
          cd client
          npm install
          npm run lint

      # --- TESTS BACK-END ---
      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Installation et Linting Back-end (FastAPI/Ruff)
        run: |
          cd server
          pip install ruff
          ruff check .
